name: untitled1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter_colorpicker: ^1.0.3
  google_nav_bar: ^5.0.6
  like_button: ^2.0.5
  flutter_staggered_animations: ^1.1.1
  photo_view: ^0.14.0
  flutter_carousel_slider:
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.6
  getwidget: ^3.0.1
  path:
#  ext_storage: ^1.0.3
#  ext_storage: ^1.0.3
  shared_preferences: ^2.0.15
#  ext_storage:
#  flutter_staggered_animations:
#  flutter_svg:
  flutter_file_manager: ^0.2.0
  dio:
  path_provider:
  image_gallery_saver:
  permission_handler: ^10.2.0
  image_picker:
  google_fonts: ^3.0.1
  unicons: ^2.1.0
  get:
  get_storage:
  sqflite:
  intl:
  flutter:
    sdk: flutter
  cupertino_icons:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: ArbFONTS-ReemKufi-SemiBold
      fonts:
        - asset: assets/fonts/ArbFONTS-ReemKufi-SemiBold.ttf
  assets:
    - assets/Images/